[tool.codespell]
check-filenames = true
check-hidden = true
ignore-words = '.codespellignore'
skip = 'build,.git,.mypy_cache,.pytest_cache'

[tool.tomlsort]
all = true
ignore_case = true
trailing_comma_inline_array = true
