.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. _Association pour la Sauvegarde du Léman: https://www.facebook.com/AssociationPourLaSauvegardeDuLeman?__cft__%5b0%5d=AZWD82clJ-iQDhoqhYWKWFTPK9KfCmcafgzxheHCiG4GZ7oOowbgO3Mdf4mLBK65Mcor9zwyxzYVb-uHSplcimn97NZYVXVId-mesFKZVNMHYIPj9hDW_dj0LyVZ_xOBNye7po2ot5l-c6PhE8SysbHePTdoOFCXKgQnR_F6ExBkgKzTKicqk6_JunBfiyXyVZeV2DDWOgiJXG50iFMgb53C&__tn__=-%5dK-R
.. _fonds National pour la recherche scientifique Suisse (FNS): https://www.snf.ch/fr
.. _galaxus: https://www.galaxus.ch
.. _one tree planted: https://www.facebook.com/onetreeplanted?__cft__%5b0%5d=AZWD82clJ-iQDhoqhYWKWFTPK9KfCmcafgzxheHCiG4GZ7oOowbgO3Mdf4mLBK65Mcor9zwyxzYVb-uHSplcimn97NZYVXVId-mesFKZVNMHYIPj9hDW_dj0LyVZ_xOBNye7po2ot5l-c6PhE8SysbHePTdoOFCXKgQnR_F6ExBkgKzTKicqk6_JunBfiyXyVZeV2DDWOgiJXG50iFMgb53C&__tn__=-%5dK-R
.. _participation questionnaire: http://fpse.qualtrics.com/jfe/form/SV_3E6v3cgTWULvUHk
.. _pro natura genève: https://www.facebook.com/ProNaturaGeneve?__cft__%5b0%5d=AZWD82clJ-iQDhoqhYWKWFTPK9KfCmcafgzxheHCiG4GZ7oOowbgO3Mdf4mLBK65Mcor9zwyxzYVb-uHSplcimn97NZYVXVId-mesFKZVNMHYIPj9hDW_dj0LyVZ_xOBNye7po2ot5l-c6PhE8SysbHePTdoOFCXKgQnR_F6ExBkgKzTKicqk6_JunBfiyXyVZeV2DDWOgiJXG50iFMgb53C&__tn__=-%5dK-R
.. _Prof. Daphné Bavelier: https://www.unige.ch/cisa/center/members/bavelier-daphne/
.. _Prof. Swann Pichon: https://www.hesge.ch/heds/la-heds/annuaire/swann-pichon
.. _RTS emission: https://www.rts.ch/info/sciences-tech/10593222-vision-attention-les-jeux-videos-daction-benefiques-a-nos-cerveaux.html
.. _wwf: https://www.facebook.com/WWF?__cft__%5b0%5d=AZWD82clJ-iQDhoqhYWKWFTPK9KfCmcafgzxheHCiG4GZ7oOowbgO3Mdf4mLBK65Mcor9zwyxzYVb-uHSplcimn97NZYVXVId-mesFKZVNMHYIPj9hDW_dj0LyVZ_xOBNye7po2ot5l-c6PhE8SysbHePTdoOFCXKgQnR_F6ExBkgKzTKicqk6_JunBfiyXyVZeV2DDWOgiJXG50iFMgb53C&__tn__=-%5dK-R
