.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...

.. _RTS emission: https://www.rts.ch/info/sciences-tech/10593222-vision-attention-les-jeux-videos-daction-benefiques-a-nos-cerveaux.html
