name: doc
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install linux dependencies
        run: |
          sudo apt update
          sudo apt install -y optipng
      - name: Install package
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip install --progress-bar off -r requirements.txt
      - name: Build doc
        run: make html
      - name: Prune sphinx environment
        run: rm -R ./build/html/.doctrees
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: doc-build
          path: ./build/html

  deploy:
    if: github.event_name == 'push'
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: doc-build
          path: ./doc-build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./doc-build
          target-folder: .
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
          single-commit: true
          force: true
